export const predictionMarketAbi = [
  {
    type: "function",
    name: "createRound",
    stateMutability: "nonpayable",
    inputs: [
      { name: "pool", type: "address" },
      { name: "duration", type: "uint32" },
      { name: "twapWindow", type: "uint32" },
      { name: "statement", type: "string" },
    ],
    outputs: [{ name: "roundId", type: "uint256" }],
  },
  {
    type: "function",
    name: "resolveRound",
    stateMutability: "nonpayable",
    inputs: [{ name: "roundId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "getRound",
    stateMutability: "view",
    inputs: [{ name: "roundId", type: "uint256" }],
    outputs: [
      {
        name: "round",
        type: "tuple",
        components: [
          { name: "pool", type: "address" },
          { name: "startTimestamp", type: "uint40" },
          { name: "endTimestamp", type: "uint40" },
          { name: "twapWindow", type: "uint32" },
          { name: "startTwapTick", type: "int24" },
          { name: "endTwapTick", type: "int24" },
          { name: "totalYesStake", type: "uint128" },
          { name: "totalNoStake", type: "uint128" },
          { name: "winningStake", type: "uint128" },
          { name: "distributable", type: "uint128" },
          { name: "claimedWinningStake", type: "uint128" },
          { name: "claimedPayout", type: "uint128" },
          { name: "resolved", type: "bool" },
          { name: "voided", type: "bool" },
          { name: "outcomeYes", type: "bool" },
          { name: "statement", type: "string" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "activeRoundForPool",
    stateMutability: "view",
    inputs: [{ name: "pool", type: "address" }],
    outputs: [{ name: "roundId", type: "uint256" }],
  },
  {
    type: "function",
    name: "totalRoundsCreated",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "totalRoundsResolved",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "totalVolume",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "totalUniqueParticipants",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "event",
    name: "RoundCreated",
    anonymous: false,
    inputs: [
      { indexed: true, name: "roundId", type: "uint256" },
      { indexed: true, name: "pool", type: "address" },
      { indexed: false, name: "startTimestamp", type: "uint40" },
      { indexed: false, name: "endTimestamp", type: "uint40" },
      { indexed: false, name: "duration", type: "uint32" },
      { indexed: false, name: "twapWindow", type: "uint32" },
      { indexed: false, name: "startTwapTick", type: "int24" },
      { indexed: false, name: "statement", type: "string" },
    ],
  },
  {
    type: "event",
    name: "RoundResolved",
    anonymous: false,
    inputs: [
      { indexed: true, name: "roundId", type: "uint256" },
      { indexed: false, name: "voided", type: "bool" },
      { indexed: false, name: "outcomeYes", type: "bool" },
      { indexed: false, name: "startTwapTick", type: "int24" },
      { indexed: false, name: "endTwapTick", type: "int24" },
      { indexed: false, name: "totalYesStake", type: "uint256" },
      { indexed: false, name: "totalNoStake", type: "uint256" },
      { indexed: false, name: "distributable", type: "uint256" },
      { indexed: false, name: "protocolFee", type: "uint256" },
    ],
  },
] as const;

export const uniswapV3FactoryAbi = [
  {
    type: "event",
    name: "PoolCreated",
    anonymous: false,
    inputs: [
      { indexed: true, name: "token0", type: "address" },
      { indexed: true, name: "token1", type: "address" },
      { indexed: true, name: "fee", type: "uint24" },
      { indexed: false, name: "tickSpacing", type: "int24" },
      { indexed: false, name: "pool", type: "address" },
    ],
  },
] as const;

export const uniswapV3PoolAbi = [
  {
    type: "function",
    name: "slot0",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "sqrtPriceX96", type: "uint160" },
      { name: "tick", type: "int24" },
      { name: "observationIndex", type: "uint16" },
      { name: "observationCardinality", type: "uint16" },
      { name: "observationCardinalityNext", type: "uint16" },
      { name: "feeProtocol", type: "uint8" },
      { name: "unlocked", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "observe",
    stateMutability: "view",
    inputs: [{ name: "secondsAgos", type: "uint32[]" }],
    outputs: [
      { name: "tickCumulatives", type: "int56[]" },
      { name: "secondsPerLiquidityCumulativeX128s", type: "uint160[]" },
    ],
  },
  {
    type: "function",
    name: "token0",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "token1",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "fee",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint24" }],
  },
  {
    type: "function",
    name: "liquidity",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint128" }],
  },
  {
    type: "event",
    name: "Swap",
    anonymous: false,
    inputs: [
      { indexed: true, name: "sender", type: "address" },
      { indexed: true, name: "recipient", type: "address" },
      { indexed: false, name: "amount0", type: "int256" },
      { indexed: false, name: "amount1", type: "int256" },
      { indexed: false, name: "sqrtPriceX96", type: "uint160" },
      { indexed: false, name: "liquidity", type: "uint128" },
      { indexed: false, name: "tick", type: "int24" },
    ],
  },
] as const;

export const erc20MetadataAbi = [
  {
    type: "function",
    name: "symbol",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "function",
    name: "decimals",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
  },
] as const;
